trigger:

  branches:
   include:
    #  - develop
     - master

pr:
 branches:
   include:
    #  - develop
     - alops-test

pool:
  name: Seacity

variables:
- name: 'alops-licenseid'
  value: '$(RDN-AlopsLicense)'

steps:
- checkout: self
  clean: true


- task: ALOpsDockerCreate@1
  displayName: 'ALOPS - Create Docker Image' # It will reuse the image if already exists, or build one if it doesn't.
  inputs:
    artifacttype: Sandbox
    licensefile: '$(RDN-DEV-License)'

- task: ALOpsDockerStart@1
  displayName: 'ALOPS - Start Docker Container' # No need to provide any details - it will get the details from previous step

- task: ALOpsDockerWait@1
  displayName: 'ALOPS - Wait for Docker Container to start'
  inputs:
    search_string: 'Ready for connections!'

#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

# - task: ALOpsLicenseImport@1
#   displayName: 'ALOPS - License Import'
#   inputs:
#     usedocker: true
#     license_path: '$(bc.license)'  # more info: https://www.youtube.com/watch?v=iVLOerdCuwA&t=3078s


- task: ALOpsAppCompiler@2
  displayName: 'Compile boilerplate App'
  inputs:
    artifacttype: Sandbox
    appversiontemplate: '24.4.19.*'
    updatebuildnumber: True
    appfilenametemplate: '%APP_NAME%_%APP_VERSION%.app'
    # targetproject: 'alopsboilerplate.AL/app.json'  
    alsourcepath: 'alopsboilerplate.AL/app.json' #$(System.DefaultWorkingDirectory) 
    versionselect: Weekly
    alcodeanalyzer: CodeCop,UICop
    ruleset: "$(System.DefaultWorkingDirectory)/rdn-customers.ruleset.json"


- task: ALOpsAppPublish@1
  displayName: 'Publish Boilerplate App'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    skip_verification: true

- task: ALOpsAppCompiler@2
  displayName: 'Compile boilerplate dependant App'
  inputs:
    artifacttype: Sandbox
    appversiontemplate: '24.4.19.*'
    updatebuildnumber: True
    appfilenametemplate: '%APP_NAME%_%APP_VERSION%.app'
    # targetproject: 'alopsboilerplatedepApp.AL/app.json' 
    alsourcepath: 'alopsboilerplatedepApp.AL/app.json' #$(System.DefaultWorkingDirectory) 
    versionselect: Weekly
    alcodeanalyzer: CodeCop,UICop
    ruleset: "$(System.DefaultWorkingDirectory)/rdn-customers.ruleset.json"


- task: ALOpsAppPublish@1
  displayName: 'Publish Dep App'
  inputs:
    usedocker: true
    nav_artifact_app_filter: '*.app'
    skip_verification: true

#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

- task: ALOpsDockerRemove@1
  displayName: 'Remove Docker Container'
  enabled: true
  condition: always()
